module.exports = {
	btcconfig: {
		protocol: '',
		host: '',
		user: '',
		password: '',
		port: '',
		method: '',
		UserKey: "RempicExchangeWalletJHGJI^",
		AdminAddress: "",
		hotAdminAddress: '',
		AdminKey: "",
		Apikey: "",
		APIUrl: process.env.BTC,
		APIHash: process.env.BTC_HASH,
		minBal: 0.0001,
	},

	ethconfig: {
		protocol: '',
		host: 'https://sepolia.infura.io/v3/124421d666204f5b88f80ea404d851aa',
		user: '',
		password: '',
		port: '',
		method: '',
		UserKey: "jhio0jwejujsdd",
		AdminAddress: "",
		hotAdminAddress: '',
		AdminKey: "",
		Apikey: "2A3XCM8FE2KJPYX6HSVW892NBXNBSWQ8KU",
		APIUrl: 'https://api.etherscan.io/v2/api?chainid=11155111',
		Usdt_token: process.env.ETH_USDT_TOKEN,
		// txnLink: 'https://sepolia.etherscan.io/tx/',
		minBal: 0.005,
		minTokenLimit: 20 

	},
	solconfig: {
		protocol: '',
		host: '',
		user: '',
		password: '',
		port: '',
		method: '',
		UserKey: "RempicExchangeWalletJHGJI^",
		AdminAddress: "",
		hotAdminAddress: '',
		AdminKey: "",
		Apikey: "",
		APIUrl: process.env.SOL,
		minBal: 0.003, 
	   // minBal: 0.00003,

		FEE_BUFFER_LAMPORTS :0.000005,

	},

	ltcconfig: {
		protocol: '',
		host: '',
		user: '',
		password: '',
		port: '',
		method: '',
		UserKey: "RempicExchangeWalletJHGJI^",
		AdminAddress: "",
		hotAdminAddress: '',
		AdminKey: "",
		Apikey: "",
		APIUrl: '',
		minBal: 0.001,
	},

	adaconfig: {
		protocol: '',
		host: '',
		user: '',
		password: '',
		port: '',
		method: '',
		UserKey: "RempicExchangeWalletJHGJI^",
		AdminAddress: "",
		hotAdminAddress: '',
		AdminKey: "",
		Apikey: process.env.ADA_APIKEY,
		APIUrl: process.env.ADA_TESTNET_API_URL,
		network: 0, // 0 = testnet, mainnet = 1
		txnLink: '',
	     minBal: 2, 
		//minBal: 0.0000010,
	}
}
